name: A workflow for my hello world file
on : push

jobs:
  build:
    name: Hello world action
    if: github.repository == 'divineforge/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"